version: 2
jobs:
  build:
    docker:
      - image: centos:latest
    steps:
      - checkout
      - run:
          name: Update
          command: .circleci/build.sh update
      - run:
          name: Validate spec file
          command: yum install -y rpmlint && rpmlint -v *.spec
      - run:
          name: Install build dependencies
          command: yum install -y yum-utils && yum-builddep -y *.spec
      - run:
          name: Build RPM
          command: make clean && tar -czvf /tmp/tmp.tar.gz && rpmbuild -ta /tmp/tmp.tar.gz
      - run:
          name: Collect artifacts
          command: mkdir -p /root/dist && find /root -name \*.rpm | xargs -I ARG mv -v ARG /root/dist/
      - persist_to_workspace:
          root: /root/dist
          paths: ./*.rpm
  test:
    docker:
      - image: centos:latest
    steps:
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Installation test
          command: yum install -y /dist/*.rpm
      - store_artifacts:
          path: /dist
          destination: dist/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
